export const GET_TERMS = 'GET_TERMS';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';
export const GET_PRIVACY_POLICY_SUCCESS = 'GET_PRIVACY_POLICY_SUCCESS';

export const API_ERROR = 'API_ERROR';