require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '11.0'

target 'fanectApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'Firebase/Analytics';
  # pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor'

  pod 'react-native-webrtc', :path => '../node_modules/@videosdk.live/react-native-webrtc'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-nodemediaclient', :path => '../node_modules/react-native-nodemediaclient'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'opentok-react-native', :path => '../node_modules/opentok-react-native'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'agora-react-native-rtm', :path => '../node_modules/agora-react-native-rtm'

  target 'fanectAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
