export const DEACTIVATE_PROFILE = 'DEACTIVATE_PROFILE';
export const DEACTIVATE_PROFILE_SUCCESS = 'DEACTIVATE_PROFILE_SUCCESS';
export const DEACTIVATE_PROFILE_FAILURE = 'DEACTIVATE_PROFILE_FAILURE';

export const API_ERROR = "API_ERROR"
