/* USERS */
export const GET_USERS = 'GET_USERS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_SUBSCRIPTIONS = 'GET_USER_SUBSCRIPTIONS';
export const GET_USER_SUBSCRIPTIONS_SUCCESS = 'GET_USER_SUBSCRIPTIONS_SUCCESS';

export const API_ERROR = 'API_ERROR';
