/* USERS */
export const GET_CELEBRITIES = 'GET_CELEBRITIES';
export const GET_CELEBRITIES_PROFILE = 'GET_CELEBRITIES_PROFILE';
export const GET_CELEBRITIES_PROFILE_SUCCESS =
  'GET_CELEBRITIES_PROFILE_SUCCESS';
export const GET_CELEBRITIES_SUCCESS = 'GET_CELEBRITIES_SUCCESS';
export const GET_CELEBRITIES_SUBSCRIPTIONS = 'GET_CELEBRITIES_SUBSCRIPTIONS';
export const GET_CELEBRITIES_SUBSCRIPTIONS_SUCCESS =
  'GET_CELEBRITIES_SUBSCRIPTIONS_SUCCESS';
export const SEARCH_CELEBRITIES = 'SEARCH_CELEBRITIES';
export const SEARCH_CELEBRITIES_SUCCESS = 'SEARCH_CELEBRITIES_SUCCESS';

export const API_ERROR = 'API_ERROR';
