//Subscriptions

export const SUBSCRIBE_TO_CELEBRITY = 'SUBSCRIBE_TO_CELEBRITY';
export const UNSUBSCRIBE_FROM_CELEBRITY = 'UNSUBSCRIBE_FROM_CELEBRITY';
export const BUY_CELEBRITY_SUBSCRIPTIONS = 'BUY_CELEBRITY_SUBSCRIPTIONS';
export const APPLY_GIFT_CODE = 'APPLY_GIFT_CODE';
export const GET_DETAILS_OF_SUBSCRIPTION = 'GET_DETAILS_OF_SUBSCRIPTION';
export const GET_DETAILS_OF_SUBSCRIPTION_SUCCESS ='GET_DETAILS_OF_SUBSCRIPTION_SUCCESS';
export const UNSUBSCRIBE_FROM_CELEBRITY_SUCCESS ='UNSUBSCRIBE_FROM_CELEBRITY_SUCCESS';
export const SUBSCRIBE_TO_CELEBRITY_SUCCESS = 'SUBSCRIBE_TO_CELEBRITY_SUCCESS';
export const BUY_CELEBRITY_SUBSCRIPTIONS_SUCCESS ='BUY_CELEBRITY_SUBSCRIPTIONS_SUCCESS';

export const API_ERROR = 'API_ERROR';
